---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./cilium/ks.yaml
  - ./kubelet-csr-approver/ks.yaml
  - ./reloader/ks.yaml
  - ./descheduler/ks.yaml
  - ./priorityclass.yaml
  - ./node-feature-discovery/ks.yaml
  - ./intel-device-plugin/ks.yaml
  - ./metrics-server/ks.yaml
  - ./k8tz/ks.yaml
