---
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
#https://trash-guides.info/Sonarr/sonarr-setup-quality-profiles/
sonarr:
  default:
    base_url: http://sonarr.default.svc.cluster.local
    api_key: !env_var SONARR__API_KEY
    delete_old_custom_formats: true
    replace_existing_custom_formats: true
    quality_definition:
      type: series
    quality_profiles:
      - name: WEB-DL (1080p)
        reset_unmatched_scores:
          enabled: true
      - name: WEB-DL (2160p)
        reset_unmatched_scores:
          enabled: true

    custom_formats:
      # Unwanted
      - trash_ids:
          - 85c61753df5da1fb2aab6f2a47426b09 # BR-DISK
          - 9c11cd3f07101cdba90a2d81cf0e56b4 # LQ
          - 47435ece6b99a0b477caf360e79ba0bb # x265(HD)
          - fbcb31d8dabd2a319072b84fc0b7249c # Extras
          - 9b27ab6498ec0f31a3353992e19434ca # DV (WEBDL)
          - 2016d1676f5ee13a5b7257ff86ac9a93 # SDR
        quality_profiles:
          - name: WEB-DL (2160p)
            score: -10000
          - name: WEB-DL (1080p)
            score: -10000
      - trash_ids:
          - 9b27ab6498ec0f31a3353992e19434ca # DV (WEBDL)
          - 2016d1676f5ee13a5b7257ff86ac9a93 # SDR
        quality_profiles:
          - name: WEB-DL (2160p)
            score: -10000
      # Misc
      - trash_ids:
          - ec8fa7296b64e8cd390a1600981f3923 # Repack/Proper
        quality_profiles:
          - name: WEB-DL (1080p)
            score: 5
          - name: WEB-DL (2160p)
            score: 5
      - trash_ids:
          - eb3d5cc0a2be0db205fb823640db6a3c # Repack2
        quality_profiles:
          - name: WEB-DL (1080p)
            score: 6
          - name: WEB-DL (2160p)
            score: 6
      - trash_ids:
          - 44e7c4de10ae50265753082e5dc76047 # Repack3
        quality_profiles:
          - name: WEB-DL (1080p)
            score: 7
          - name: WEB-DL (2160p)
            score: 7
      # Streaming Services
      - trash_ids:
          - f67c9ca88f463a48346062e8ad07713f # ATVP
          - 89358767a60cc28783cdc3d0be9388a4 # DSNP
        quality_profiles:
          - name: WEB-DL (1080p)
            score: 100
          - name: WEB-DL (2160p)
            score: 100
      - trash_ids:
          - 81d1fbf600e2540cee87f3a23f9d3c1c # MAX
        quality_profiles:
          - name: WEB-DL (1080p)
            score: 90
          - name: WEB-DL (2160p)
            score: 90
      - trash_ids:
          - a880d6abc21e7c16884f3ae393f84179 # HMAX
          - 3ac5d84fce98bab1b531393e9c82f467 # QIBI
        quality_profiles:
          - name: WEB-DL (1080p)
            score: 80
          - name: WEB-DL (2160p)
            score: 80
      - trash_ids:
          - d660701077794679fd59e8bdf4ce3a29 # AMZN
        quality_profiles:
          - name: WEB-DL (1080p)
            score: 70
          - name: WEB-DL (2160p)
            score: 70
      - trash_ids:
          - d34870697c9db575f17700212167be23 # NF
          - 1656adc6d7bb2c8cca6acfb6592db421 # PCOK
          - c67a75ae4a1715f2bb4d492755ba4195 # PMTP
          - 1efe8da11bfd74fbbcd4d8117ddb9213 # STAN
        quality_profiles:
          - name: WEB-DL (1080p)
            score: 60
          - name: WEB-DL (2160p)
            score: 60
      - trash_ids:
          - 77a7b25585c18af08f60b1547bb9b4fb # CC
          - 4e9a630db98d5391aec1368a0256e2fe # CRAV
          - 36b72f59f4ea20aad9316f475f2d9fbb # DCU
          - 7a235133c87f7da4c8cccceca7e3c7a6 # HBO
          - f6cce30f1733d5c8194222a7507909bb # HULU
          - 0ac24a2a68a9700bcb7eeca8e5cd644c # iT
          - b2b980877494b560443631eb1f473867 # NLZ
          - c30d2958827d1867c73318a5a2957eb1 # RED
          - ae58039e1319178e6be73caab5c42166 # SHO
          - 5d2317d99af813b6529c7ebf01c83533 # VDL
          - fb1a91cdc0f26f7ca0696e0e95274645 # OViD
        quality_profiles:
          - name: WEB-DL (1080p)
            score: 50
          - name: WEB-DL (2160p)
            score: 50
      - trash_ids:
          - 43b3cf48cb385cd3eac608ee6bca7f09 # UHD Streaming Boost
        quality_profiles:
          - name: WEB-DL (2160p)
            score: 20
      - trash_ids:
          - d2d299244a92b8a52d4921ce3897a256 # UHD Streaming Cut
        quality_profiles:
          - name: WEB-DL (2160p)
            score: -20
      # HQ Release Groups
      - trash_ids:
          - e6258996055b9fbab7e9cb2f75819294 # WEB Tier 01
        quality_profiles:
          - name: WEB-DL (1080p)
            score: 1700
          - name: WEB-DL (2160p)
            score: 1700
      - trash_ids:
          - 58790d4e2fdcd9733aa7ae68ba2bb503 # WEB Tier 02
        quality_profiles:
          - name: WEB-DL (1080p)
            score: 1650
          - name: WEB-DL (2160p)
            score: 1650
      - trash_ids:
          - d84935abd3f8556dcd51d4f27e22d0a6 # WEB Tier 03
          - d0c516558625b04b363fa6c5c2c7cfd4 # WEB Scene
        quality_profiles:
          - name: WEB-DL (1080p)
            score: 1600
          - name: WEB-DL (2160p)
            score: 1600
      # HDR Formats
      - trash_ids:
          - 7878c33f1963fefb3d6c8657d46c2f0a # DV HDR10
          - 6d0d8de7b57e35518ac0308b0ddf404e # DV
          - 1f733af03141f068a540eec352589a89 # DV HLG
          - 27954b0a80aab882522a88a4d9eae1cd # DV SDR
        quality_profiles:
          - name: WEB-DL (2160p)
            score: 1500
      - trash_ids:
          - a3d82cbef5039f8d295478d28a887159 # HDR10+
        quality_profiles:
          - name: WEB-DL (2160p)
            score: 600
      - trash_ids:
          - 3497799d29a085e2ac2df9d468413c94 # HR10
          - 3e2c4e748b64a1a1118e0ea3f4cf6875 # HRD
          - bb019e1cd00f304f80971c965de064dc # HRD (Undefined)
          - 2a7e3be05d3861d6df7171ec74cad727 # PQ
          - 17e889ce13117940092308f48b48b45b # HLG
        quality_profiles:
          - name: WEB-DL (2160p)
            score: 500

# https://trash-guides.info/Radarr/radarr-setup-quality-profiles/
radarr:
  default:
    base_url: http://radarr.default.svc.cluster.local
    api_key: !env_var RADARR__API_KEY
    delete_old_custom_formats: true
    replace_existing_custom_formats: true
    quality_definition:
      type: movie
    quality_profiles:
      - name: HD Bluray + WEB
        reset_unmatched_scores:
          enabled: true

      - name: UHD Bluray + WEB
        reset_unmatched_scores:
          enabled: true

    custom_formats:
      # Unwanted
      - trash_ids:
          - ed38b889b31be83fda192888e2286d83 # BR-DISK
          - 90a6f9a284dff5103f6346090e6280c8 # LQ
          - dc98083864ea246d05a42df0d05f81cc # x265(HD)
          - b8cd450cbfa689c0259a01d9e29ba3d6 # 3D

        quality_profiles:
          - name: HD Bluray + WEB
            score: -10000
          - name: UHD Bluray + WEB
            score: -10000
      - trash_ids:
          - bfd8eb01832d646a0a89c4deb46f8564 # Upscaled
        quality_profiles:
          - name: UHD Bluray + WEB
            score: -10000
      # Misc
      - trash_ids:
          - e7718d7a3ce595f289bfee26adc178f5 # Repack/Proper
        quality_profiles:
          - name: HD Bluray + WEB
            score: 5
          - name: UHD Bluray + WEB
            score: 5
      - trash_ids:
          - ae43b294509409a6a13919dedd4764c4 # Repack2
        quality_profiles:
          - name: HD Bluray + WEB
            score: 6
          - name: UHD Bluray + WEB
            score: 6

      # Streaming Services
      - trash_ids:
          - 84272245b2988854bfb76a16e60baea5 # DSNP
          - 509e5f41146e278f9eab1ddaceb34515 # HBO
          - 5763d1b0ce84aff3b21038eea8e9b8ad # HMAX
          - 6a061313d22e51e0f25b7cd4dc065233 # MAX
          - 526d445d4c16214309f0fd2b3be18a89 # Hulu
          - 170b1d363bd8516fbf3a3eb05d4faff6 # NF
          - bf7e73dd1d85b12cc527dc619761c840 # Pathe
          - c9fd353f8f5f1baf56dc601c4cb29920 # PCOK
          - e36a0ba1bc902b26ee40818a1d59b8bd # PMTP
          - c2863d2a50c9acad1fb50e53ece60817 # STAN
          - fbca986396c5e695ef7b2def3c755d01 # OViD
          - f6ff65b3f4b464a79dcc75950fe20382 # CRAV
          - b3b3a6ac74ecbd56bcdbefa4799fb9df # AMZN
          - 40e9380490e748672c2522eaaeb692f7 # ATVP
        quality_profiles:
          - name: HD Bluray + WEB
            score: 0
          - name: UHD Bluray + WEB
            score: 0
      - trash_ids:
          - cc5e51a9e85a6296ceefe097a77f12f4 # BCORE
        quality_profiles:
          - name: HD Bluray + WEB
            score: 15
          - name: UHD Bluray + WEB
            score: 15
      - trash_ids:
          - 16622a6911d1ab5d5b8b713d5b0036d4 # CRiT
          - 2a6039655313bf5dab1e43523b62c374 # MA
        quality_profiles:
          - name: HD Bluray + WEB
            score: 20
          - name: UHD Bluray + WEB
            score: 20

      # Movie Versions
      - trash_ids:
          - 570bc9ebecd92723d2d21500f4be314c # Remaster
          - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
          - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
          - 9d27d9d2181838f76dee150882bdc58c # Masters of jcinema
          - db9b4c4b53d312a3ca5f1378f6440fc9 # Vinegar Syndrome
        quality_profiles:
          - name: HD Bluray + WEB
            score: 25
          - name: UHD Bluray + WEB
            score: 25
      - trash_ids:
          - 957d0f44b592285f26449575e8b1167e # Special Edition
        quality_profiles:
          - name: HD Bluray + WEB
            score: 125
          - name: UHD Bluray + WEB
            score: 125
      - trash_ids:
          - eecf3a857724171f968a66cb5719e152 # IMAX
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
        quality_profiles:
          - name: HD Bluray + WEB
            score: 800
          - name: UHD Bluray + WEB
            score: 800

      # HQ Release Groups
      - trash_ids:
          - ed27ebfef2f323e964fb1f61391bcb35 # HD Bluray Tier 01
        quality_profiles:
          - name: HD Bluray + WEB
            score: 1800
      - trash_ids:
          - c20c8647f2746a1f4c4262b0fbbeeeae # HD Bluray Tier 02
        quality_profiles:
          - name: HD Bluray + WEB
            score: 1750
      - trash_ids:
          - 5608c71bcebba0a5e666223bae8c9227 # HD Bluray Tier 03
          - c20f169ef63c5f40c2def54abaf4438e # WEB Tier 01
        quality_profiles:
          - name: HD Bluray + WEB
            score: 1700
      - trash_ids:
          - 403816d65392c79236dcb6dd591aeda4 # WEB Tier 02
        quality_profiles:
          - name: HD Bluray + WEB
            score: 1650
          - name: UHD Bluray + WEB
            score: 1650
      - trash_ids:
          - af94e0fe497124d1f9ce732069ec8c3b # WEB Tier 03
        quality_profiles:
          - name: HD Bluray + WEB
            score: 1600
          - name: UHD Bluray + WEB
            score: 1600
      - trash_ids:
          - 4d74ac4c4db0b64bff6ce0cffef99bf0 # UHD Bluray Tier 01
        quality_profiles:
          - name: UHD Bluray + WEB
            score: 1800
      - trash_ids:
          - a58f517a70193f8e578056642178419d # UHD Bluray Tier 02
        quality_profiles:
          - name: UHD Bluray + WEB
            score: 1750
      - trash_ids:
          - e71939fae578037e7aed3ee219bbe7c1 # UHD Bluray Tier 03
          - c20f169ef63c5f40c2def54abaf4438e # WEB Tier 01
        quality_profiles:
          - name: UHD Bluray + WEB
            score: 1700
