---
apiVersion: v1
kind: Secret
metadata:
  name: prowlarr-volsync
  namespace: default
stringData:
  RESTIC_REPOSITORY: ${RESTIC_REPOSITORY}/prowlarr
  RESTIC_PASSWORD: ${RESTIC_PASSWORD}
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: prowlarr
  namespace: default
spec:
  sourcePVC: config-prowlarr-0
  trigger:
    schedule: "0 7 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 10
    repository: prowlarr-volsync
    retain:
      daily: 7
      within: 3d
    volumeSnapshotClassName: zfs-block
    storageClassName: zfs-block
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
