---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - jetstack.yaml
  - ingress-nginx.yaml
  - bjw-s.yaml
  - cilium.yaml
  - postfinance.yaml
  - descheduler.yaml
  - stakater.yaml
  - external-dns.yaml
  - rook-ceph.yaml
  - jameswynn.yaml
  - backube.yaml
  - piraeus.yaml
  - kubernetes-sigs-nfd.yaml
  - intel.yaml
  - kubernetes-sigs-metrics-server.yaml
  - kyverno.yaml
  - prometheus-community.yaml
  - grafana.yaml
  - k8s-gateway.yaml
  - democratic-csi.yaml
  - weave-gitops.yaml
  - k8tz.yaml
  - bitnami.yaml
  - cloudnative-pg.yaml
