---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: electrolama-zigbee-device
  namespace: kube-system
spec:
  rules:
    - name: electrolama.zigbee
      labels:
        aeotec.feature.node.kubernetes.io/zigbee: "true"
      matchFeatures:
        - feature: usb.device
          matchExpressions:
            class: { op: In, value: ["ff"] }
            vendor: { op: In, value: ["1a86"] }
            device: { op: In, value: ["7523"] }
